<?php
DEFINE('LOGFILE', 'dialogflow.log');
DEFINE('CREDENTIALS_FILE', 'yourproject.json');
DEFINE('BOTENGINE_TOKEN', '');
DEFINE('DIALOGFLOW_PROJECT', '');
DEFINE('BOTENGINE_FALLBACK_ID', '');
DEFINE('BOTENGINE_USERSAY_ATTRIBUTE', 'userSay');
?>
